##--------------------------------------##
##--             SETTINGS             --##
##-- (for the structure of the model) --##
##--------------------------------------##

BLACK.HISPANIC.OTHER = c('black','hispanic','other')

##-- FOR COLLAPSED CONTINUUM --#

SETTINGS.COLLAPSED.CONTINUUM = list(AGE_CUTOFFS = c(13,25,35,45,55,Inf),
                RACES = BLACK.HISPANIC.OTHER,
                RISK_STRATA = c('never_IDU', 'active_IDU', 'IDU_in_remission'),
                CONTINUUM_OF_CARE = c('undiagnosed', 'undiagnosed_from_prep', 'diagnosed'), # 'unsuppressed', 'suppressed'),
                CD4_STRATA = c('acute', 'chronic'),#c('acute','chronic','AIDS'),#c('acute','chronic'),
                SUBPOPULATIONS = NULL,
                SEXES = c('heterosexual_male', 'msm', 'female'))
SETTINGS.COLLAPSED.CONTINUUM$ACTIVE_IDU_STATE = SETTINGS.COLLAPSED.CONTINUUM$RISK_STRATA[2]
SETTINGS.COLLAPSED.CONTINUUM$CHRONIC_STATES = SETTINGS.COLLAPSED.CONTINUUM$CD4_STRATA[2]
SETTINGS.COLLAPSED.CONTINUUM$ACUTE_STATES = setdiff(SETTINGS.COLLAPSED.CONTINUUM$CD4_STRATA, SETTINGS.COLLAPSED.CONTINUUM$CHRONIC_STATES)
SETTINGS.COLLAPSED.CONTINUUM$UNDIAGNOSED_NO_PREP = SETTINGS.COLLAPSED.CONTINUUM$CONTINUUM_OF_CARE[1]
SETTINGS.COLLAPSED.CONTINUUM$UNDIAGNOSED_FROM_PREP = SETTINGS.COLLAPSED.CONTINUUM$CONTINUUM_OF_CARE[2]
SETTINGS.COLLAPSED.CONTINUUM$UNDIAGNOSED_STATES = c(SETTINGS.COLLAPSED.CONTINUUM$UNDIAGNOSED_NO_PREP, SETTINGS.COLLAPSED.CONTINUUM$UNDIAGNOSED_FROM_PREP)
SETTINGS.COLLAPSED.CONTINUUM$FIRST_DIAGNOSED_STATE = SETTINGS.COLLAPSED.CONTINUUM$CONTINUUM_OF_CARE[3]
SETTINGS.COLLAPSED.CONTINUUM$AGES = make.age.strata(SETTINGS.COLLAPSED.CONTINUUM$AGE_CUTOFFS)
SETTINGS.COLLAPSED.CONTINUUM$DIAGNOSED_STATES = setdiff(SETTINGS.COLLAPSED.CONTINUUM$CONTINUUM_OF_CARE, SETTINGS.COLLAPSED.CONTINUUM$UNDIAGNOSED_STATES)
SETTINGS.COLLAPSED.CONTINUUM$IS_CONTINUUM_COLLAPSED = T
SETTINGS.COLLAPSED.CONTINUUM$VERSION = 'collapsed_1.0'

##-- FOR EXPANDED CONTINUUM --#

SETTINGS.EXPANDED.CONTINUUM = list(AGE_CUTOFFS = SETTINGS.COLLAPSED.CONTINUUM$AGE_CUTOFFS,
                                    RACES = BLACK.HISPANIC.OTHER,
                                    RISK_STRATA = SETTINGS.COLLAPSED.CONTINUUM$RISK_STRATA,
                                    CONTINUUM_OF_CARE = c('undiagnosed', 'undiagnosed_from_prep', 'unengaged', 'engaged_unsuppressed', 'engaged_suppressed', 'disengaged'),
                                    CD4_STRATA = SETTINGS.COLLAPSED.CONTINUUM$CD4_STRATA,
                                    SUBPOPULATIONS = SETTINGS.COLLAPSED.CONTINUUM$SUBPOPULATIONS,
                                    SEXES = SETTINGS.COLLAPSED.CONTINUUM$SEXES)

SETTINGS.EXPANDED.CONTINUUM$ACTIVE_IDU_STATE = SETTINGS.COLLAPSED.CONTINUUM$ACTIVE_IDU_STATE
SETTINGS.EXPANDED.CONTINUUM$CHRONIC_STATES = SETTINGS.COLLAPSED.CONTINUUM$CHRONIC_STATES
SETTINGS.EXPANDED.CONTINUUM$ACUTE_STATES = SETTINGS.COLLAPSED.CONTINUUM$ACUTE_STATES
SETTINGS.EXPANDED.CONTINUUM$UNDIAGNOSED_NO_PREP = SETTINGS.COLLAPSED.CONTINUUM$UNDIAGNOSED_NO_PREP
SETTINGS.EXPANDED.CONTINUUM$UNDIAGNOSED_FROM_PREP = SETTINGS.COLLAPSED.CONTINUUM$UNDIAGNOSED_FROM_PREP
SETTINGS.EXPANDED.CONTINUUM$UNDIAGNOSED_STATES = SETTINGS.COLLAPSED.CONTINUUM$UNDIAGNOSED_STATES
SETTINGS.EXPANDED.CONTINUUM$FIRST_DIAGNOSED_STATE = SETTINGS.EXPANDED.CONTINUUM$CONTINUUM_OF_CARE[3]
SETTINGS.EXPANDED.CONTINUUM$AGES = make.age.strata(SETTINGS.EXPANDED.CONTINUUM$AGE_CUTOFFS)
SETTINGS.EXPANDED.CONTINUUM$DIAGNOSED_STATES = setdiff(SETTINGS.EXPANDED.CONTINUUM$CONTINUUM_OF_CARE, SETTINGS.EXPANDED.CONTINUUM$UNDIAGNOSED_STATES)
SETTINGS.EXPANDED.CONTINUUM$SUPPRESSED_STATES = 'engaged_suppressed'
SETTINGS.EXPANDED.CONTINUUM$ENGAGED_STATES = c("engaged_unsuppressed", "engaged_suppressed")
SETTINGS.EXPANDED.CONTINUUM$IS_CONTINUUM_COLLAPSED = F
SETTINGS.EXPANDED.CONTINUUM$VERSION = 'expanded_1.0'


##-- CHOOSE WHICH ONE TO USE --#

SETTINGS = SETTINGS.COLLAPSED.CONTINUUM
#SETTINGS = SETTINGS.EXPANDED.CONTINUUM